fixes #314 - add names to routes
redeclipse/base pull request #1102
Opened 2020-09-30 11:12 UTC by Jigoku

Fixes #314 

Changes proposed in this request:
- `showroutenames` (toggle particle display of name)
- `routenameblend` (blend value for particle text)
- `routenames` (list of route names)

eg; map var: `routenames easy medium hard`
then becomes:

* routeid 0  = easy
* routeid 1  = medium
* routeid 2  = hard

This would now allow for a UI to choose the route by a proper name. 

One thing i'm not sure of (couldn't figure it out), is whether the particle text should only be drawn on the first node/link for the `showroutenames`, but here it just draws above each node.

![2020-09-30-120511_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/94678189-056b1600-0316-11eb-9c5d-de678ac08d1c.png)
![2020-09-30-120512_1920x1080_scrot](https://user-images.githubusercontent.com/1535179/94678202-08660680-0316-11eb-960c-0e9c8cc8399f.png)

2020-09-30 11:34 UTC, qreeves commented
Maybe we should just display it on the first one and show the currently selected route on the HUD? I'd like to make sure the words are capitalised when appropriate as well.

2020-09-30 11:50 UTC, Jigoku commented
Yeah, looks a bit messy with the route name spammed all over the place. I did spend a while trying to find a way to limit drawing to only the first ent within the routeid, but had no luck figuring it out.

2020-10-02 10:50 UTC, qreeves requested changes

2020-10-02 10:50 UTC, qreeves commented on src/game/entities.cpp
> +        }
Might get you to fix the formatting here first, either moving the if up on to the loop line or indenting the if block, and putting a new line before the break.

2020-10-02 11:02 UTC, Jigoku commented on src/game/entities.cpp
> +        }
Done

2020-10-02 11:31 UTC, merged