Mouse acceleration
redeclipse/base pull request #1267
Opened 2021-05-30 16:25 UTC by anengineer1

Fixes #

Changes proposed in this request:
- [description]
Due to how fast this game can be, I find Quake Live's mouse acceleration to work quite well in Red Eclipse.

2021-05-30 16:41 UTC, q009 requested changes

2021-05-30 16:41 UTC, q009 commented on src/game/game.cpp
> +	        float accelsensitivity = 1;
Please fix indentation in various parts of the PR

2021-05-30 16:41 UTC, q009 commented on src/engine/rendergl.cpp
> +    glFinish();
What's the reason behind change here?

2021-05-30 16:52 UTC, anengineer1 commented on src/engine/rendergl.cpp
> +    glFinish();
it is important for the framemillis to be calculated for the mouse acceleration to work; it is required to have the same accel no matter your framerate.

With the previous code, framemillis was only calculated when enabling the frametimer.

2021-05-30 17:01 UTC, anengineer1 commented on src/game/game.cpp
> +	        float accelsensitivity = 1;
Sorry for my ignorance, but when checking at the file itself, it seems to be correctly indented ->

https://github.com/anengineer1/base/blob/mouse_acceleration/src/game/game.cpp

I'm having a close look at the file at the moment

2021-05-30 17:12 UTC, q009 commented on src/game/game.cpp
> +	        float accelsensitivity = 1;
Make sure you're using spaces, not tabs

2021-05-30 18:13 UTC, anengineer1 commented on src/game/game.cpp
> +	        float accelsensitivity = 1;
Sorry for the delay, seems all is in order now, I just deleted all the tabs and pressed "space", I'm removing the autotab indent from my editor.

2021-05-30 18:30 UTC, q009 approved these changes
LGTM

2021-05-30 18:44 UTC, q009 requested changes
Actually, one more thing: squash those changes into one or two commits please. It's quite a mess

2021-05-30 18:52 UTC, anengineer1 commented
You mean, the 7 or so attempts in removing the tabs? I'm learning how to do so, I'm on it

2021-05-30 19:14 UTC, anengineer1 commented
I think I solved the thingy; I'm learning a lot today.

Please, tell me if it is suitable now.

2021-05-31 07:22 UTC, q009 approved these changes

2021-05-31 09:58 UTC, qreeves requested changes
I really appreciate the contribution, and this is probably something we've needed for some time. Please just bear without our nit-picking as we try to keep our codebase fairly pure.

2021-05-31 09:58 UTC, qreeves commented on src/engine/rendergl.cpp
> +    framemillis = getclockmillis() - totalmillis;
My question here: is `framemillis` really necessary when you have `curtime`?

2021-05-31 09:58 UTC, qreeves commented on src/game/game.cpp
> +    // Section regarding mouse acceleration
I'd prefer these variables to be a little shorter, so maybe `mouseaccel*`? Also, seeing as `mouseaccelerationfactor` is the switch variable as well, just call it plain `mouseaccel`.

2021-05-31 09:58 UTC, qreeves commented on src/game/game.cpp
> +                if(mouseaccelerationfactor)
I try to make non boolean or integer variables use a comparison check rather than an implicit boolean, so I would prefer `if(mouseaccel > 0)`.

2021-05-31 09:58 UTC, qreeves commented on src/game/game.cpp
> +                     // restores it again.
We value screen space with the code, so please try to compress these comments in to one or two lines.

2021-05-31 09:58 UTC, qreeves commented on src/game/game.cpp
> +                     float inv_sensitivity = 1.0f / sensitivity;
I'm probably being really pedantic, but again, compressed into fewer lines would be better. With them all being the same type you don't really need to declare it more than once. Also, I prefer variables without underscores as it is an awkward character to type when you're bashing out code.

2021-05-31 09:58 UTC, qreeves commented on src/game/game.cpp
> +                     if (adjusted_speed_pxms > 0)
Convention with the codebase is to not have a space between `if` and the opening bracket. Ditto for lines 2464 and 2483.

2021-05-31 09:58 UTC, qreeves commented on src/game/game.cpp
> +                // end accel
This comment isn't really necessary. I know it's a pain we don't comment a lot, and I've let the comments above slide because they're very speculative changes, but we try to make it so the code speaks for itself and rely on fewer comments to make it quicker to read through actual code.

2021-05-31 09:58 UTC, qreeves commented on src/engine/rendergl.cpp
> +    framemillis = getclockmillis() - totalmillis;
[19:52] Q009: @Quin curtime is scaled
[19:52] Q009: So, just changing the gamespeed would have an effect on the mouse acceleration when using curtime to calculate it(edited)
[19:52] Q009: Which is definitely not what one would want

2021-06-01 14:49 UTC, anengineer1 commented
Sorry for the delay, I took this oportunity to further test the code just in case, everything should be in order now.

Pls, tell me if something more is necessary.

2021-06-02 07:05 UTC, qreeves approved these changes

2021-06-02 07:06 UTC, qreeves commented
No problem, we all go at our own pace around here, so no need to rush. Thanks so much for pushing the requested changes, this is now approved for merging and will get done in my next round of merges (I'll need to test it).

2021-06-12 12:56 UTC, merged

2021-06-12 13:08 UTC, qreeves commented on src/game/game.cpp
> +                         accelsensitivity += 0.0f;
I merged this and took a proper look at it, and this line is pretty much a non-statement. Is it supposed to be something else?

2021-06-12 14:19 UTC, anengineer1 commented on src/game/game.cpp
> +                         accelsensitivity += 0.0f;
You are right.

This is not the first time I implemented this mouse acceleration and the maintainer of another project prefered to have it that way to make it more explicit so I wrote the mouse acceleration in a very similar way than in that other game engine I helped with.

Feel free to change it.

2021-06-12 14:20 UTC, anengineer1 commented on src/game/game.cpp
> +                         accelsensitivity += 0.0f;
If you want me to change it just tell me and I will gladly will.

2021-06-12 15:19 UTC, qreeves commented on src/game/game.cpp
> +                         accelsensitivity += 0.0f;
Nah, all good, I'll do it in my tidy up commit later. Just wanted to make sure it wasn't a typo.

2021-12-03 17:21 UTC, q009 commented
Due to performance issues, I had to revert the change.
The ``glFinish`` call in ``gl_drawframe`` drops the framerate by about 30%

2021-12-08 14:33 UTC, anengineer1 commented
Thank you a lot for letting me know!

Once I have time again, I will work on it.

Do you think the cause might be using the frametime counter? it is very important for making the accel frame-independent.

Tesseract game has a mouse acceleration implementation, I will take a look at its source code and see what they have done

Sorry for taking so long in answering.

2021-12-08 14:36 UTC, q009 commented
The cause is using relying on ``glFinish``. It stalls the entire pipeline until the processing on the GPU is finished, drastically reducing the performance. Perhaps try using ``curtime`` instead to base the acceleration on, or ``elapsedmillis``.

2021-12-08 19:25 UTC, anengineer1 commented
Thank you a lot! I'll take a look at it!

I'll will be very absent during this month but I will get my hands dirty as soon as I can

2022-01-04 15:42 UTC, anengineer1 commented
Greetings, I've made some testing using curtime instead of framemillis and it seems it works as planned:

- Acceleration curves are consistent not mattering the framerate
- I also tested the accel on high graphics to force inconsitent fluctuation and the acceleration curve is also consistent and aiming it's still a pleasure.

My branch is updated but I don't know how to update the thing on the pull request.


Sorry and thank you