Clean up
redeclipse/base pull request #1304
Opened 2021-10-30 18:55 UTC by tygyh

Fixes #

Changes proposed in this request:
- Remove some redundant bool comvertions

2021-10-30 19:20 UTC, q009 requested changes
Don't use blind string replace.

2021-10-30 19:20 UTC, q009 commented on src/engine/client.cpp
> +ICOMMAND(0, isonline, "", (), intret(curpeer));
The idea here was to limit the return value to either 1 or 0.

2021-10-30 19:20 UTC, q009 commented on bin/redeclipse.app/Contents/Frameworks/SDL2.framework/Versions/A/Headers/SDL_endian.h
> +  __asm__("bswapl %0; bswapl %1; xchgl %0,%1": "=r"(v.s.a), "=r"(v.s.b):"0"(v.s.a),
It appears you just blindly replaced all " ;" with just ";".  It's asking for trouble and might mess with syntax of various scripts and whatnot

2021-10-30 19:20 UTC, q009 commented on src/engine/command.cpp
> +        intret(val); \
Once again, altering the return value of functions. As well as in many other places.

2021-10-30 19:20 UTC, q009 commented on src/engine/renderparticles.cpp
> +        loopi(15 + (p->fill))
This is very, very wrong. Don't use blind string replace.

2021-12-24 23:54 UTC, qreeves commented
Dangling PR without a response to changes requested. Closing.

2021-12-24 23:54 UTC, closed without merging