add moveselents command
redeclipse/base pull request #1314
Opened 2021-12-11 06:21 UTC by Jigoku

2021-12-11 13:18 UTC, qreeves requested changes
Only one issue to fix prior to merge.

2021-12-11 13:18 UTC, qreeves commented on src/engine/world.cpp
> +ICOMMAND(0, moveselents, "fff", (float *x, float *y, float *z), vec v(*x, *y, *z); moveselents(v));
No newline at end of file.

2021-12-11 15:51 UTC, Jigoku commented on src/engine/world.cpp
> +ICOMMAND(0, moveselents, "fff", (float *x, float *y, float *z), vec v(*x, *y, *z); moveselents(v));
whoops, fixed.

2021-12-12 14:40 UTC, qreeves approved these changes

2021-12-12 14:40 UTC, merged