Update profile.cfg
redeclipse/base pull request #1412
Opened 2023-02-14 23:54 UTC by dc-de

Unifying naming

2023-03-07 06:12 UTC, qreeves requested changes

2023-03-07 06:12 UTC, qreeves commented on config/ui/profile.cfg
> +            uitext "Welcome to Red Eclipse ^f7."
You can remove the "` ^f7`"

2023-03-07 17:02 UTC, dc-de reviewed
Removed double text color

2023-03-07 17:04 UTC, dc-de commented on config/ui/profile.cfg
> +            uitext "Welcome to Red Eclipse ^f7."
yeah sorry that is doubled, removed in patch #7c3d869

2023-03-08 14:27 UTC, qreeves approved these changes

2023-03-08 14:28 UTC, merged