README needed some changing
redeclipse/base pull request #1428
Opened 2023-05-11 06:12 UTC by StupidRepo

I just made it look a little bit better.

2023-05-11 06:17 UTC, qreeves requested changes
Rest seems fine.

2023-05-11 06:18 UTC, qreeves commented on readme.txt
> +The project is a free and open source game built using OpenAL and OpenGL which allows it to be ported to many platforms; you can [download a package](https://redeclipse.net/download) for Windows, GNU
But feel free to add OpenAL to the list still.

2023-05-11 14:21 UTC, StupidRepo commented on readme.txt
> +* Completely free; download [here](https://redeclipse.net/)
I don't either, but I didn't really like the original. It didn't fit in. Besides, a little below that it mentions that the game is free. So I guess I could remove it?

2023-05-11 15:05 UTC, StupidRepo commented
I don't know why I did that, lol.

2023-05-11 15:09 UTC, StupidRepo reviewed
Hoping this makes that stupid warning go away

2023-05-12 00:43 UTC, qreeves commented on readme.txt
> +* Completely free; download [here](https://redeclipse.net/)
No, the top of the file is basically the "TLDR" version of what is below, and typically how games promote themselves online. In general, this file is supposed to be copy/pasted when setting up a new landing page.

2023-05-12 00:44 UTC, qreeves requested changes

2023-05-12 00:44 UTC, qreeves commented on readme.txt
> -* Download for free at https://redeclipse.net/
Please reinstate this line.

2023-05-13 12:24 UTC, closed without merging