weapons.cpp now uses a bitmask instead of strings
redeclipse/base pull request #1591
Opened 2024-09-11 22:21 UTC by nochinator

Changes proposed in this request:
- modified weapons.cpp to use a bitmask system instead of a string mechanism for defining and selecting weapons.

discussion at https://discord.com/channels/224638962050793474/1281415133595439146 (the custom weapons discussion in think tank)

2024-09-12 01:38 UTC, MirceaKitsune commented
It's nice to see the base change is as simple as I hoped. I presume the total number of weapon slots remains the same for now which should be fine: One important aspect was the ability to reorder weapons and choose what is a starting weapon or loadout or powerup using any models, I wonder if that limitation is lifted. A few things will need to be changed otherwise such as the loadout section of the player customization menu, weapon specific mutators like Kaboom or Medieval might need to be rethought and ideally turned into an arena selector that allows picking any weapon.

2024-09-13 02:40 UTC, qreeves commented on src/game/weapons.cpp
> +    ICOMMAND(0, ammo, "ii", (int *n, int *m), intret(isweap(*n) ? game::player1->weapammo[*n][clamp(*m, 0, W_A_MAX-1)] : -1));
Nice catch.

2024-09-13 02:44 UTC, qreeves requested changes
Great pull request, minor changes requested for code style and missed bits/pieces.

2024-09-13 02:44 UTC, qreeves commented on src/game/weapons.cpp
> +
I'd rather not have functions separated by three new line characters unless there are interstitial comments.

2024-09-13 02:44 UTC, qreeves commented on src/game/weapons.cpp
> +
Three new lines here too.

2024-09-13 02:44 UTC, qreeves commented on src/game/weapons.cpp
> +
Another three lines.

2024-09-13 02:44 UTC, qreeves commented on src/game/weapons.cpp
> +    ICOMMAND(0, weapon, "ii", (int *a, int *b), weaponswitch(game::player1, *a, *b));
This has further ramifications than just within the source code.

Can you update the defaults in `config/*.cfg` please?

2024-09-13 11:03 UTC, nochinator commented on src/game/weapons.cpp
> +    ICOMMAND(0, weapon, "ii", (int *a, int *b), weaponswitch(game::player1, *a, *b));
I searched every usage of it and could find nothing that would break it. They all construct it from other functions in `weapons.cpp` that now return ints instead of strings.

I've also built the code and tested everything I could think that would be related to it and had no issues. this includes the loadout menu, weapon switching, weapon switch with number keys, side mouse buttons, and the weapon wheel.
Everything worked as expected and there were no errors in the in-game console or terminal used to start it.

2024-09-14 05:32 UTC, qreeves commented on src/game/weapons.cpp
> +    ICOMMAND(0, weapon, "ii", (int *a, int *b), weaponswitch(game::player1, *a, *b));
Alrighty. I'll check it during my next rounds. Thanks for clarifying.

2024-09-14 05:35 UTC, qreeves requested changes
Last review and we're good to go.

2024-09-14 05:35 UTC, qreeves commented on src/game/weapons.cpp
> -        loopi(W_ALL) if(weaplist.find(i) < 0) weaplist.add(i); // make sure all weapons have a slot
There are concerns from other developers regarding removing comments that explain things not immediately obvious.

Could you please restore these before I merge?

2024-09-14 05:35 UTC, qreeves commented on src/game/weapons.cpp
> -    ICOMMAND(0, weapslot, "i", (int *o), intret(slot(game::player1, *o >= 0 ? *o : game::player1->weapselect))); // -1 = weapselect slot
Restore comments.

2024-09-14 05:35 UTC, qreeves commented on src/game/weapons.cpp
> -            loopi(W_ALL) // only loop the amount of times we have weaps for
Restore comments.

2024-09-14 05:35 UTC, qreeves commented on src/game/weapons.cpp
> -                    if(a < 0 && weapskipempty && !d->hasweap(n, w, 3)) continue; // skip empty when scrolling
Restore comments.

2024-09-16 02:30 UTC, merged